### ISSUE TITLE
Tools and tech stack

### ISSUE THREAD

**Issue by ronniesong0809** [psu-agile-group/FTP-Client#2]
We need to have a discussion on the language and tools that we want to use for this project

Language opinions:
* Java
* C++
* C#

**Comment by guhilot** [comment]
Java -> intelliJ
I am fine with C++ too

**Comment by ronniesong0809** [comment]
**Decision made**: Java with IntelliJ

![image](https://user-images.githubusercontent.com/6004123/60568240-27e03f00-9d21-11e9-8419-1765c7bd95cd.png)
